---
logs:
  configs:
    - clients:
      - basic_auth:
          password: "{{ grafana_api_key }}"
          username: "{{ grafana_logs_user }}"
        url: "{{ grafana_logs_url }}"
      name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: integrations/node_exporter_direct_scrape
          static_configs:
            - targets:
                - localhost
              labels:
                instance: hostname
                __path__: /var/log/*.log
                job: integrations/node_exporter
      target_config:
        sync_period: 10s

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 30s
    remote_write:
    - url: "{{ grafana_metrics_remote_write_url}}"
      basic_auth:
        username: "{{ grafana_metrics_user }}"
        password: "{{ grafana_api_key }}"


integrations:
  node_exporter:
    enabled: true
    rootfs_path: /
    sysfs_path: /sys
    procfs_path: /proc
